# action.yml
name: "Docker CMD Format"
description: "Format a string as a Docker CMD array."
inputs:
  command:
    description: >-
      Command to be passed as the CMD to the ECS/Fargate container image.
      Any string will try to be converted to a Docker CMD array.
      An unspaced Docker CMD array will also work. Ex:
      ["python","manage.py","migrate"]
    required: true
outputs:
  output:
    description: "Formatted command string"
runs:
  using: "node16"
  main: "index.js"
