on:
  workflow_call:
    inputs:
      build_args:
        required: false
        default: ""
        description: "A newline delimited (| in yaml) string of Docker build-args"
        type: string
      version:
        required: true
        description: "GeoMatch tag to build for."
        type: string

# TODO: gha Cache doesn't work for tags?
# https://github.com/docker/build-push-action/issues/433

env:
  GEOMATCH_VERSION: ${{ inputs.version }}
  # Frustrating workaround becuase we can't use secrets as inputs.
  # See https://stackoverflow.com/questions/73606841/github-actions-passing-secret-as-input-for-reusable-workflow
  DOCKER_BUILD_ARGS: |
    GEOMATCH_VERSION=${{ inputs.version }}
    CONTAINER_PORT=${{ secrets.AWS_GEOMATCH_ECR_CONTAINER_PORT }}
    ${{ secrets.GEOMATCH_DOCKER_BUILD_ARGS }}
    ${{ inputs.build_args }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_BUILD_ROLE_ARN }}
          role-session-name: ReleaseBuild
          role-duration-seconds: 1000
      - name: Docker Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        # Creates alias of 'docker build' to 'docker buildx build'
        with:
          install: true
      - name: Build 'production' image
        id: docker_build_production
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
          tags: |
            "${{ secrets.AWS_GEOMATCH_ECR_REPO_URL }}:${{ inputs.version }}"
            "${{ secrets.AWS_GEOMATCH_ECR_REPO_URL }}:latest"
          target: production
          push: true
          load: false
          cache-from: "type=registry,ref=${{ secrets.AWS_GEOMATCH_ECR_REPO_URL }}:latest-cache"
          cache-to: "type=registry,mode=max,ref=${{ secrets.AWS_GEOMATCH_ECR_REPO_URL }}:latest-cache"
      # Consider using github action cache instead. See:
      # https://github.com/docker/build-push-action/issues/286#issuecomment-892900431
      # https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
