on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "GeoMatch version tag to build for (i.e. v0.0.1)."
        type: string

jobs:
  terraform-deploy:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_TERRAFORM_PLAN_ROLE_ARN }}
          role-session-name: ECSDeployTerraformPlan
          role-duration-seconds: 1000
      - name: Terraform Init
        run: terraform init -backend-config=./prod.backend.auto.tfvars
      - name: Terraform Plan
        run: terraform plan -var="geomatch_version=${{ inputs.version }}" -out prod.plan
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_TERRAFORM_ECS_DEPLOY_ROLE_ARN }}
          role-session-name: ECSDeployTerraformApply
          role-duration-seconds: 1000
      - name: Terraform Apply
        run: terraform apply prod.plan
      - name: Get ECS Run Task Config
        uses: GeoMatch/deployment/.github/actions/ssm-get-param@main
        id: config
        with:
          ssm-name: ${{ secrets.AWS_GEOMATCH_ECS_RUN_TASK_CONFIG_SSM_NAME }}
      - name: Wait for ECS Deploy
        uses: GeoMatch/deployment/.github/actions/ecs-wait-services-stable@main
        with:
          ecs-run-task-config: ${{ steps.config.outputs.value }}
      - if: ${{ always() }}
        run: rm prod.plan || true
  ecs-run-collectstatic:
    name: "ECS Run collectstatic"
    needs: terraform-deploy
    uses: ./.github/workflows/ecs-run-sync.yml
    secrets: inherit
    with:
      command: "python manage.py collectstatic --no-input"
