on:
  workflow_call:
    inputs:
      command:
        required: true
        description: >-
          Command to be passed as the CMD to the ECS/Fargate container image.
          Any string will try to be converted to a Docker CMD array.
          An unspaced Docker CMD array will also work. Ex:
          ["python","manage.py","migrate"]
        type: string

# TODO create user workflow that masks secret: https://github.com/actions/runner/issues/643

jobs:
  ecs-run:
    name: "ECS Run"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ECS_RUN_TASK_ROLE_ARN }}
          role-session-name: ECSRunFargateTask
          role-duration-seconds: 1000
      - name: Set up secret file
        env:
          ARN: ${{ secrets.AWS_GEOMATCH_ECS_RUN_TASK_CONFIG_SSM_ARN }}
        run: |
          echo ${{secrets.AWS_GEOMATCH_ECS_RUN_TASK_CONFIG_SSM_ARN}} | sed 's/./& /g'
      - name: Get ECS Run Task Config
        uses: GeoMatch/github-actions/actions/ssm-get-param@main
        id: config
        with:
          ssm-name: ${{ secrets.AWS_GEOMATCH_ECS_RUN_TASK_CONFIG_SSM_NAME }}
      - name: Run command on ECS
        uses: GeoMatch/github-actions/actions/ecs-run-sync@main
        with:
          ecs-run-task-config: ${{ steps.config.outputs.value }}
          command: ${{ inputs.command }}
