on:
  workflow_call:
    inputs:
      cpu:
        required: false
        description: "New CPU (1 VCPU = 1024 here)."
        type: string
        default: ""
      memory:
        required: false
        description: "New memory (in MiB)."
        type: string
        default: ""
      terraform_directory:
        required: true
        description: "Terraform project directory (i.e. './terraform')"
        type: string

# Essentially, just calls terraform apply with these new variables
jobs:
  fetch-latest-release:
    runs-on: ubuntu-latest
    outputs:
      latest_release_tag: ${{ steps.latest-release.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest release
        id: latest-release
        uses: actions/github-script@v7
        with:
          script: |
            const repo = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            };
            const response = await github.rest.repos.getLatestRelease(repo);
            const release = response.data;
            console.log('Latest release:', release.tag_name);
            core.setOutput('tag_name', release.tag_name);
  prepare-vars:
    runs-on: ubuntu-latest
    outputs:
      extra_vars: ${{ steps.set-vars.outputs.extra_vars }}
    steps:
      - name: Set vars
        id: set-vars
        shell: bash
        run: |
          EXTRA_VARS=""
          if [[ -n "${{ inputs.cpu }}" ]]; then
            EXTRA_VARS+="--var 'app_cpu=${{ inputs.cpu }}' "
          fi
          if [[ -n "${{ inputs.memory }}" ]]; then
            EXTRA_VARS+="--var 'app_memory=${{ inputs.memory }}' "
          fi
          echo "extra_vars=$EXTRA_VARS" >> $GITHUB_OUTPUT
  terraform-scale:
    name: "ECS Terraform Scale"
    needs: [fetch-latest-release, prepare-vars]
    uses: ./.github/workflows/ecs-terraform-deploy.yml
    secrets: inherit
    with:
      version: ${{ needs.fetch-latest-release.outputs.latest_release_tag }}
      extra_vars: ${{ needs.prepare-vars.outputs.extra_vars }}
      terraform_directory: ${{ inputs.terraform_directory }}
