# Fetches the latest release (via git tag)
# Used to know the currently launched version

on:
  workflow_call:
    outputs:
      latest_release:
        description: "Get latest release tag from repository"
        value: ${{ jobs.fetch-latest-release.outputs.latest_release_tag }}

jobs:
  fetch-latest-release:
    runs-on: ubuntu-latest
    outputs:
      latest_release_tag: ${{ steps.latest-release.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest release
        id: latest-release
        uses: actions/github-script@v7
        with:
          script: |
            const repo = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            };
            const response = await github.rest.repos.getLatestRelease(repo);
            const release = response.data;
            console.log('Latest release:', release.tag_name);
            core.setOutput('tag_name', release.tag_name);
